In [60]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [61]:
import numpy as np
import pandas as pd
import math 
import random


In [62]:
#reading data form csv

train_path='train.csv'
test_path='test.csv'
train_raw_data=pd.read_csv(train_path)
test_raw_data=pd.read_csv(test_path)
#print(train_raw_data)



In [63]:
# extracting traing labels and train data witout labels

Y_labels=train_raw_data['SalePrice'].copy()
train_raw_data=train_raw_data.drop(['SalePrice'],axis=1) # axis=1 for vertically axis=0 for horizontally



In [64]:
# finding the null containing cell

V=train_raw_data.isnull().sum()
#V.to_csv('V.csv',index=True)


In [65]:
#visualing data
train_raw_data.MSSubClass.unique()
test_raw_data.MSSubClass.unique()
train_raw_data.SaleType.isnull().sum()


array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  85,  80, 160,  75,
       180,  40], dtype=int64)

array([ 20,  60, 120, 160,  80,  30,  50,  90,  85, 190,  45,  70,  75,
       180,  40, 150], dtype=int64)

0

In [66]:
# maping data to numerical value 
 ###SaleType
train_raw_data.SaleType.isnull().sum()
train_raw_data.SaleType.unique()
train_raw_data['SaleType']=train_raw_data['SaleType'].map({ 'WD':10, 'CWD':9, 'VWD':8,'New':7, 'COD':6, 'Con':5, 'ConLw':4,'ConLI':3, 'ConLD':2, 'Oth':1})
#print(train_raw_data['SaleType'])

0

array(['WD', 'New', 'COD', 'ConLD', 'ConLI', 'CWD', 'ConLw', 'Con', 'Oth'],
      dtype=object)

In [67]:
###SaleCondition
train_raw_data.SaleCondition.isnull().sum()
train_raw_data.SaleCondition.unique()
train_raw_data['SaleCondition']=train_raw_data.SaleCondition.map({ 'Normal': 6, 'Abnorml':1, 'AdjLand':5 ,'Alloca':3, 'Family':4, 'Partial':2})

#print(train_raw_data['SaleCondition'])

0

array(['Normal', 'Abnorml', 'Partial', 'AdjLand', 'Alloca', 'Family'],
      dtype=object)

In [68]:
###MSSubClass (Buliding type  (Identifies the type of dwelling involved in the sale))
train_raw_data.MSSubClass.isnull().sum()   #Already in neumerical 


0

In [69]:
###LotConfig
train_raw_data.LotConfig.isnull().sum()
train_raw_data['LotConfig']=train_raw_data.LotConfig.map({'Inside':2,'Corner':1,'CulDSac':6,'FR2':5,'FR3':4})

0

In [70]:
###BldgType (type of dwelling)(quite similar to buliding type)
train_raw_data.BldgType.isnull().sum()
train_raw_data.BldgType.unique()
train_raw_data["BldgType"]=train_raw_data.BldgType.map({"1Fam":65,"2fmCon":70,"Duplex":75,'TwnhsE':85,'Twnhs':80})
train_raw_data['BldgType'].isnull().sum()

0

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

0

In [71]:
###HouseStyle  (style of dwelling (room architecture))
train_raw_data.HouseStyle.isnull().sum()
train_raw_data.HouseStyle.unique()
train_raw_data['HouseStyle']=train_raw_data.HouseStyle.map({"1Story":50,"1.5Fin":75, "2Story":80,"2.5Fin":100,"2.5Unf":90,"1.5Unf":70,"SFoyer":65,'SLvl':55})

0

array(['2Story', '1Story', '1.5Fin', '1.5Unf', 'SFoyer', 'SLvl', '2.5Unf',
       '2.5Fin'], dtype=object)

In [72]:
### Room information
#BedroomAbvGr (Bedrooms number)
train_raw_data['BedroomAbvGr'].isnull().sum()  #already in number
train_raw_data['TotRmsAbvGrd'].isnull().sum()  #already in number
#Kitchen
train_raw_data['KitchenAbvGr'].isnull().sum()  #already in number
train_raw_data['KitchenQual'].isnull().sum()
train_raw_data['KitchenQual'].unique()

train_raw_data['KitchenQual']=train_raw_data['KitchenQual'].map({"Ex":5,"Gd":4,"TA":3,"Fa":2,"Po":1})
train_raw_data['KitchenQual'].isnull().sum()

###Baths
train_raw_data['FullBath'].isnull().sum()
train_raw_data['HalfBath'].isnull().sum()

##marging Baths
train_raw_data['TotalBaths']=train_raw_data['FullBath']+0.5*train_raw_data['HalfBath']
train_raw_data=train_raw_data.drop(['FullBath','HalfBath'],axis=1)

train_raw_data['TotalBaths'].isnull().sum()

0

0

0

0

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

0

0

0

0

In [73]:
### RoofStyle (type of roof)
train_raw_data.RoofStyle.isnull().sum()
train_raw_data.RoofStyle.unique()
train_raw_data['RoofStyle']=train_raw_data.RoofStyle.map({'Flat':4,'Gable':3,'Gambrel':2,'Hip':5,'Mansard':6,'Shed':1})

0

array(['Gable', 'Hip', 'Gambrel', 'Mansard', 'Flat', 'Shed'], dtype=object)

In [74]:
### RoofMatl  (roof material)
train_raw_data.RoofMatl.isnull().sum()
train_raw_data.RoofMatl.unique()
train_raw_data['RoofMatl']=train_raw_data.RoofMatl.map({'ClyTile':60,'CompShg':80,'Membran':40,'Metal':70,'Roll':65,'Tar&Grv':55,'WdShake':50,'WdShngl':45})

0

array(['CompShg', 'WdShngl', 'Metal', 'WdShake', 'Membran', 'Tar&Grv',
       'Roll', 'ClyTile'], dtype=object)

In [75]:
###Foundation (type of foundation)
train_raw_data.Foundation.isnull().sum()
train_raw_data.Foundation.unique()
train_raw_data['Foundation']=train_raw_data.Foundation.map({'BrkTil':2,'CBlock':3,'PConc':4,'Slab':5,'Stone':6,'Wood':1})
train_raw_data.Foundation.isnull().sum()

0

array(['PConc', 'CBlock', 'BrkTil', 'Wood', 'Slab', 'Stone'], dtype=object)

0

In [76]:
###BsmtQual (Height of the basement)
train_raw_data.BsmtQual.isnull().sum()
train_raw_data.BsmtQual.unique()
#imputing missing values with most frequent values
train_raw_data['BsmtQual']=train_raw_data['BsmtQual'].fillna(train_raw_data['BsmtQual'].value_counts().index[0])
train_raw_data.BsmtQual.unique()

train_raw_data['BsmtQual']=train_raw_data.BsmtQual.map({'Ex':5,'Gd':4,'TA':3,'Fa':2, 'Po':1,'NA':0})


37

array(['Gd', 'TA', 'Ex', nan, 'Fa'], dtype=object)

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [77]:
###BsmtCond  (general condition of the basement)
train_raw_data.BsmtCond.isnull().sum()
train_raw_data['BsmtCond']=train_raw_data['BsmtCond'].fillna(train_raw_data['BsmtCond'].value_counts().index[0])
train_raw_data.BsmtCond.unique()

train_raw_data['BsmtCond']=train_raw_data.BsmtCond.map({'Ex':5,'Gd':4,'TA':3,'Fa':2, 'Po':1,'NA':0})

37

array(['TA', 'Gd', 'Fa', 'Po'], dtype=object)

In [78]:
### combining the basemet condition
train_raw_data['BsmtCondComb']=train_raw_data['BsmtQual']*train_raw_data['BsmtCond']
train_raw_data=train_raw_data.drop(['BsmtCond','BsmtQual'],axis=1)

In [79]:
###Heating
train_raw_data.Heating.isnull().sum()
train_raw_data['Heating']=train_raw_data.Heating.map({'Floor':6,'GasA':3,'GasW':2,'Grav':5,'OthW':1,'Wall':4})



0

In [80]:
#HeatingQC
train_raw_data.HeatingQC.isnull().sum()
train_raw_data['HeatingQC']=train_raw_data['HeatingQC'].map({'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1})

0

In [81]:
###marging Heating and HeatinQc
train_raw_data['HeatingComb']=train_raw_data['Heating']*train_raw_data['HeatingQC']
train_raw_data=train_raw_data.drop(['Heating','HeatingQC'],axis=1)

In [82]:
###centralAir
train_raw_data.CentralAir.isnull().sum()
train_raw_data['CentralAir']=train_raw_data.CentralAir.map({'Y':1,'N':0})


0

In [83]:
###Fireplaces(number of fire places)
train_raw_data.Fireplaces.isnull().sum()
#already in numerical value

0

In [84]:
### FireplaceQu 
train_raw_data.FireplaceQu.isnull().sum()
train_raw_data['FireplaceQu']=train_raw_data['FireplaceQu'].fillna(train_raw_data['FireplaceQu'].value_counts().index[0])

train_raw_data.FireplaceQu.isnull().sum()
train_raw_data.FireplaceQu.unique()
train_raw_data['FireplaceQu']=train_raw_data.FireplaceQu.map({'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,'NA':0})

train_raw_data.FireplaceQu.isnull().sum()

690

0

array(['Gd', 'TA', 'Fa', 'Ex', 'Po'], dtype=object)

0

In [85]:
###marging  Fireplace info
train_raw_data['FireplaceComb']=train_raw_data['Fireplaces']*train_raw_data['FireplaceQu']
train_raw_data=train_raw_data.drop(['Fireplaces','FireplaceQu'],axis=1)

1

array(['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix'], dtype=object)

0

In [86]:
'''data=train_raw_data['Exterior2nd']
E2=pd.DataFrame(data=data)
E2.to_csv('E2.csv',index=True)'''

"data=train_raw_data['Exterior2nd']\nE2=pd.DataFrame(data=data)\nE2.to_csv('E2.csv',index=True)"

In [87]:
###Exterior1st & Exterior2nd
train_raw_data.Exterior1st.isnull().sum()
train_raw_data.Exterior2nd.isnull().sum()
train_raw_data.Exterior1st.unique()
train_raw_data.Exterior2nd.unique()


train_raw_data['Exterior1st']=train_raw_data.Exterior1st.map({'AsbShng':3,'AsphShn':12, 'BrkComm':7,'BrkFace':8,'CBlock':9,'CemntBd':10,'HdBoard':6,'ImStucc':16,'MetalSd':2,'Other':1,'Plywood':11,'PreCast':15,'Stone':13,'Stucco':17,'VinylSd':18,"Wd Sdng":4,'WdShing':5})
train_raw_data.Exterior1st.isnull().sum()

train_raw_data['Exterior2nd']=train_raw_data.Exterior2nd.map({'AsbShng':3,'AsphShn':12, "Brk Cmn":7,'BrkFace':8,'CBlock':9,"CmentBd":10,'HdBoard':6,'ImStucc':16,'MetalSd':2,'Other':1,'Plywood':11,'PreCast':15,'Stone':13,'Stucco':17,'VinylSd':18,'Wd Sdng':4,'Wd Shng':5})


#train_raw_data.Exterior2nd.unique()
train_raw_data.Exterior2nd.isnull().sum()

### Adding up 2 exterior and droping the second
train_raw_data["ExteriorComb"]=train_raw_data['Exterior1st']+train_raw_data['Exterior2nd']

#train_raw_data=train_raw_data.drop(['Exterior1st','Exterior2nd'],axis=1)

train_raw_data['ExteriorComb'].isnull().sum()


'''V1=Y_labels,train_raw_data['Exterior1st']
V1={
"Y_label":Y_labels,
'tr':train_raw_data['Exterior1st']
}
v1=pd.DataFrame(data=V1)
v1.to_csv('V1.csv')'''


0

0

array(['VinylSd', 'MetalSd', 'Wd Sdng', 'HdBoard', 'BrkFace', 'WdShing',
       'CemntBd', 'Plywood', 'AsbShng', 'Stucco', 'BrkComm', 'AsphShn',
       'Stone', 'ImStucc', 'CBlock'], dtype=object)

array(['VinylSd', 'MetalSd', 'Wd Shng', 'HdBoard', 'Plywood', 'Wd Sdng',
       'CmentBd', 'BrkFace', 'Stucco', 'AsbShng', 'Brk Cmn', 'ImStucc',
       'AsphShn', 'Stone', 'Other', 'CBlock'], dtype=object)

0

0

0

'V1=Y_labels,train_raw_data[\'Exterior1st\']\nV1={\n"Y_label":Y_labels,\n\'tr\':train_raw_data[\'Exterior1st\']\n}\nv1=pd.DataFrame(data=V1)\nv1.to_csv(\'V1.csv\')'

In [88]:
###ExterQual (Exterior material quality)
train_raw_data.ExterQual.isnull().sum()
train_raw_data.ExterQual.unique()
train_raw_data['ExterQual']=train_raw_data.ExterQual.map({'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1})


0

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [89]:
#ExterCond (present condition of the exterior material)
train_raw_data.ExterCond.isnull().sum()
train_raw_data.ExterCond.unique()
train_raw_data['ExterCond']=train_raw_data.ExterCond.map({'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1})


0

array(['TA', 'Gd', 'Fa', 'Po', 'Ex'], dtype=object)

In [90]:
###ExterCondComb(ExteriorQual*ExteriorCond)

train_raw_data['ExteriorCondComb']=train_raw_data['ExterCond']*train_raw_data['ExterQual']

train_raw_data=train_raw_data.drop(['ExterQual','ExterCond'],axis=1)


In [91]:
### MasVnrType (masonary veneer type)
train_raw_data.MasVnrType.isnull().sum()
train_raw_data.MasVnrType.unique()
train_raw_data['MasVnrType']=train_raw_data['MasVnrType'].fillna(train_raw_data['MasVnrType'].value_counts().index[0])

#train_raw_data.MasVnrType.unique()
train_raw_data['MasVnrType']=train_raw_data.MasVnrType.map({ 'BrkCmn':4,'BrkFace':3,'CBlock':2,'None':0,'Stone':5})


8

array(['BrkFace', 'None', 'Stone', 'BrkCmn', nan], dtype=object)

In [92]:
### MasVnrArea   
train_raw_data.MasVnrArea.isnull().sum()  #need to find the missing value

train_raw_data['MasVnrArea']=train_raw_data['MasVnrArea'].fillna(train_raw_data['MasVnrArea'].median())  

#missing data is filled with median data
#train_raw_data.MasVnrArea.unique()
train_raw_data.MasVnrArea.isnull().sum() 

8

0

In [93]:
'''### Overall External condition (ExterQual*ExterCond)
train_raw_data['OverallExterCond']=train_raw_data['ExterQual']*train_raw_data['ExterCond']'''



"### Overall External condition (ExterQual*ExterCond)\ntrain_raw_data['OverallExterCond']=train_raw_data['ExterQual']*train_raw_data['ExterCond']"

In [94]:
###OverallQual  (house quality)
train_raw_data.OverallQual.isnull().sum()
train_raw_data.OverallQual.unique()   #already in number

0

array([ 7,  6,  8,  5,  9,  4, 10,  3,  1,  2], dtype=int64)

In [95]:
### OverallCond (OVerall condition of the house)
train_raw_data.OverallCond.isnull().sum()
train_raw_data.OverallCond.unique()  #already in number

0

array([5, 8, 6, 7, 4, 2, 3, 9, 1], dtype=int64)

In [96]:
###marging overallcond
#OVerallCondComb
train_raw_data['OverallCondComb']=train_raw_data['OverallQual']*train_raw_data['OverallCond']
train_raw_data=train_raw_data.drop(['OverallQual','OverallCond'],axis=1)

In [97]:
### Zonal sitution of the building
train_raw_data.MSZoning.isnull().sum()
train_raw_data['MSZoning'].unique()
train_raw_data.MSZoning=train_raw_data.MSZoning.map({ 'A':3, "C (all)":20, 'FV':1, 'I':15,'RH':4, 'RL':10,'RP':8,'RM':6})
#print(train_raw_data.MSZoning)
train_raw_data.MSZoning.isnull().sum()


0

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

0

In [98]:
##Lot Area
train_raw_data.LotArea.isnull().sum()  ## already in numerical

0

In [99]:
###Lotshape (Property shape (checking irregualirity))
train_raw_data.LotShape.isnull().sum()
train_raw_data.LotShape.unique()
train_raw_data['LotShape']=train_raw_data.LotShape.map({'Reg':5,'IR1':4,'IR2':2,'IR3':1})
#print(train_raw_data['LotShape'])

0

array(['Reg', 'IR1', 'IR2', 'IR3'], dtype=object)

In [100]:
### LandCOntour (Flatness of the property neighbor)
train_raw_data.LandContour.isnull().sum()
train_raw_data.LandContour.unique()
train_raw_data['LandContour']=train_raw_data.LandContour.map({ 'Lvl':4, 'Bnk':3, 'HLS':2,'Low':1})

0

array(['Lvl', 'Bnk', 'Low', 'HLS'], dtype=object)

In [101]:
###LandSlope (Slope of the property land (indside the property) )
test_raw_data.LandSlope.isnull().sum()
train_raw_data.LandSlope.unique()
train_raw_data['LandSlope']=train_raw_data['LandSlope'].map({'Gtl':3,'Mod':2,'Sev':1})

0

array(['Gtl', 'Mod', 'Sev'], dtype=object)

In [102]:
##Alley access to the property (road acces)
train_raw_data.Alley.isnull().sum()  ### need to find the missing values

1369

In [103]:
##Street type
train_raw_data.Street.isnull().sum()
train_raw_data.Street.unique()
train_raw_data["Street"]=train_raw_data.Street.map({ 'Grvl':1, 'Pave':2})

0

array(['Pave', 'Grvl'], dtype=object)

In [104]:
###Utilities 
train_raw_data.Utilities.isnull().sum()
train_raw_data.Utilities.unique()
train_raw_data['Utilities']=train_raw_data.Utilities.map({'AllPub':4,'NOSewr':3,'NoSeWa':2,'ELO':1})

0

array(['AllPub', 'NoSeWa'], dtype=object)

In [105]:
###Elcetrical system
train_raw_data['Electrical'].isnull().sum()
train_raw_data['Electrical']=train_raw_data['Electrical'].fillna(train_raw_data['Electrical'].value_counts().index[0])

train_raw_data.Electrical.unique()

train_raw_data['Electrical']=train_raw_data['Electrical'].map({'SBrkr':6,'FuseA':4,'FuseF':3,'FuseP':2,'Mix':5})
train_raw_data['Electrical'].isnull().sum()

1

array(['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix'], dtype=object)

0

In [106]:
##GarageType (garage location)
train_raw_data.GarageType.isnull().sum()
#train_raw_data['']

81

In [107]:
###GrageArea
train_raw_data.GarageArea.isnull().sum()
#already in numerical

0

In [108]:
###GarageQual
train_raw_data.GarageQual.isnull().sum()

81

In [109]:
###GarageCond
train_raw_data.GarageCond.isnull().sum()

81

In [110]:
###Deck Area
train_raw_data.WoodDeckSF.isnull().sum()
#print(train_raw_data.WoodDeckSF)

0

In [111]:
### Total porcharea
##OpenPorchSF, EnclosedPorch,3SsnPorch,ScreenPorch
train_raw_data.OpenPorchSF.isnull().sum()
train_raw_data.EnclosedPorch.isnull().sum()
train_raw_data['3SsnPorch'].isnull().sum()
train_raw_data['ScreenPorch'].isnull().sum()

train_raw_data['TotalPorchArea']=train_raw_data['OpenPorchSF']+train_raw_data['EnclosedPorch']+train_raw_data['3SsnPorch']+train_raw_data['ScreenPorch']

train_raw_data=train_raw_data.drop(['OpenPorchSF','3SsnPorch','ScreenPorch','EnclosedPorch'],axis=1)

0

0

0

0

In [112]:
#pool and pool Qc
train_raw_data.PoolArea.isnull().sum() 
train_raw_data.PoolQC.isnull().sum()  ####1453 data is missing so it is out of features


0

1453

In [113]:
### MiscFeature
train_raw_data.MiscFeature.isnull().sum()  ##will not add this

1406

In [114]:
###MiscVal $vlaue of miscellaneous Feature
train_raw_data.MiscVal.isnull().sum()

0

In [115]:
###Fence
train_raw_data.Fence.isnull().sum()  # need to find out the missing data  #till now leave it

1179

In [116]:
###building new data frame
New_data_frame={

'MSZoning':train_raw_data['MSZoning'],
'Street':train_raw_data['Street'],
#'Alley':train_raw_data['Alley'],

'MSSubClass':train_raw_data['MSSubClass'],
'LotArea':train_raw_data['LotArea'],
'LandSlope':train_raw_data['LandSlope'],


'BldgType':train_raw_data['BldgType'],
'HouseStyle':train_raw_data['HouseStyle'],
'RoofStyle':train_raw_data['RoofStyle'],
'RoofMatl':train_raw_data['RoofMatl'],
'ExteriorComb':train_raw_data["ExteriorComb"],  #exterior metal comb  
'ExteriorCondComb':train_raw_data['ExteriorCondComb'], #exterior quality comb
'MasVnrType':train_raw_data['MasVnrType'],
'MasVnrArea':train_raw_data['MasVnrArea'],
'Foundation':train_raw_data['Foundation'],
'BsmtCondComb':train_raw_data['BsmtCondComb'],
'TotalBsmtSF':train_raw_data['TotalBsmtSF'],


'LowQualFinSF':train_raw_data['LowQualFinSF'],
'GrLivArea':train_raw_data['GrLivArea'],

'BedroomAbvGr':train_raw_data['BedroomAbvGr'],
'TotRmsAbvGrd':train_raw_data['TotRmsAbvGrd'],

'KitchenAbvGr':train_raw_data['KitchenAbvGr'],
'KitchenQual':train_raw_data['KitchenQual'],

#'FullBath':train_raw_data['FullBath']
#'HalfBath':train_raw_data['HalfBath']
'TotalBaths':train_raw_data['TotalBaths'],

'1stFlrSF':train_raw_data['1stFlrSF'],
'2ndFlrSF':train_raw_data['2ndFlrSF'],

'FireplaceComb':train_raw_data['FireplaceComb'],
'HeatingCOmb':train_raw_data['HeatingComb'],
'CentralAir':train_raw_data['CentralAir'],

'TotalPorchArea':train_raw_data['TotalPorchArea'],
'WoodDeckSF':train_raw_data['WoodDeckSF'],
'GarageArea':train_raw_data['GarageArea'],
'PoolArea':train_raw_data['PoolArea'],

'Utilities':train_raw_data['Utilities'],
'Electrical':train_raw_data['Electrical'],
'MiscVal':train_raw_data['MiscVal'],

'SaleType':train_raw_data['SaleType'],
'SaleCondition':train_raw_data['SaleCondition'],


'OverallCondComb':train_raw_data['OverallCondComb']

}




In [117]:
##creating the data frame and save it
New_data=pd.DataFrame(data=New_data_frame)

New_data.to_csv('New_data_frame.csv')
C1=New_data.isnull().sum()
C1.to_csv('C1.csv',index=True)

In [118]:
train_raw_data['BedroomAbvGr']
train_raw_data['BedroomAbvGr']
train_raw_data['TotalBsmtSF'].isnull().sum()

0       3
1       3
2       3
3       3
4       4
       ..
1455    3
1456    3
1457    4
1458    2
1459    3
Name: BedroomAbvGr, Length: 1460, dtype: int64

0       3
1       3
2       3
3       3
4       4
       ..
1455    3
1456    3
1457    4
1458    2
1459    3
Name: BedroomAbvGr, Length: 1460, dtype: int64

0